# Site settings
title: AgGL Kenzingen
subtitle: Arbeitsgemeinschaft für Geschichte und Landeskunde in Kenzingen e.V.
email: kilian.haemmerle@protonmail.com
description: Dies ist die Website der AgGL Kenzingen
baseurl: "/aggl_editorial" # the subpath of your site, e.g. /blog
url: "https://kilianmh.github.io" # the base hostname & protocol for your site
author: Kilian M. Haemmerle
street_address: Kirchstr. 17
city: Kenzingen
state: Baden-W&uuml;rttemberg
zip_code: 79341
country: Deutschland
# phone: (716) 555-5555

# Social settings
# 500px_url:
# facebook_url:
github_url: https://github.com/kilianmh/aggl_editorial
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugins
plugins:
- jekyll-asciidoc

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
